#!/usr/bin/expect -f
spawn "./atlassian-jira-6.3.13-x64.bin"

sleep 5

expect "You do not have administrator rights"  
send "y\r"
expect "This will install JIRA" 
send "o\r"
expect "Express Install " 
send "2\r" 
expect "Where should JIRA" 
send "\r"
expect "Default location for JIRA" 
send "\r"
expect "Configure which ports" 
send "2\r" 
expect "HTTP Port " 
send "8081\r" 
expect "Control Port" 
send "8006\r" 
expect "Install JIRA as Service?" 
send "y\r"
expect eof
send "\r\" 
interact